### ISSUE TITLE
Wiki pour faciliter les corrections/améliorations

### ISSUE THREAD

**Issue by Manu1400** [cvergne/paris-web#5]
Pour faciliter la correction d'éventuelles coquilles : 

1/ Activer l'onglet Wiki sur ce projet
2/ Déplacer le contenu sur une nouvelle page wiki

**Comment by cvergne** [comment]
Bonjour @Manu1400 

Quel type de modifications/améliorations ne sont pas possibles avec la version actuelle ? (Sachant que Github permet la modification de fichier directement via l'interface, de la même façon que le wiki).
