### ISSUE TITLE
Lier les titres aux pages idoines sur le site officiel de Paris Web

### ISSUE THREAD

**Issue by padawan** [cvergne/paris-web#6]
Sans vouloir te commander, les présentations ont chacune leur page sur le site de Paris Web, sur lesquelles nous plaçons les vidéos, les PDF, la retranscription texte etc. Ce serait bien, pour le bien de tous, de renvoyer vers la bonne page (on fait attention depuis le début à ce que ces URLs ne changent pas). Par exemple : 
https://www.paris-web.fr/2018/conferences/tempete-de-boulettes-geantes.php contient déjà un PDF et la retranscription texte.

**Comment by cvergne** [comment]
Merci pour l'information, j'ai ajouté tous les liens sur titres :)

**Comment by padawan** [comment]
Merci :)
